# Generated by Django 2.0.4 on 2018-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_remove_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.TextField(default=0),
        ),
    ]
